version: '3.4'
services:

  api:
    container_name: api
    image: api:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
      - 9001:9000
    networks:
      - docker_custom_network

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-admin:
    image: adminer
    restart: always
    ports:
      - 8082:8080

networks:
  docker_custom_network:
    external: true
